services:
  postgres:
    image: postgres:15
    container_name: postgres_viagens
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: viagens_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./BackEnd/backend
    container_name: backend_viagens
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/viagens_db
      PORT: 3000
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  frontend:
    build:
      context: ./FrontEnd/frontend
    container_name: frontend_viagens
    restart: always
    ports:
      - "3001:4173"
    depends_on:
      - backend

volumes:
  postgres_data:
